export enum StorageKeys {
  'TOKEN' = 'TOKEN',
  'LANG' = 'LANG',
  'AVAILABLETASKS' = 'AVAILABLETASKS',
  'SAVEDDATA' = 'SAVEDDATA',
  'SUBMITTED' = 'SUBMITTED',
  'IMAGES' = 'IMAGES',
  'USERPROFILE' = 'USERPROFILE',
  'USERADORG' = 'USERADORG',
  'LASTSYNCTIME' = 'LASTSYNCTIME',
}
